const champData = [
    {
        img: '/assets/BoomBot.png',
        name: "BoomBot",
        hp: 1500,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Tigeron.png',
        name: "Tigeron",
        hp: 1000,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Gotfrid.png',
        name: "Gotfrid",
        hp: 1450,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/DragonSkin.jpg',
        name: "DragonSkin",
        hp: 1400,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/FireCord.jpg',
        name: "FireCord",
        hp: 1600,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Higs.jpg',
        name: "Higs",
        hp: 1700,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/LordOfDarkness.jpg',
        name: "Lord of darkness",
        hp: 1400,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Meilis.jpg',
        name: "Meilis",
        hp: 1000,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Returner.jpg',
        name: "Returner",
        hp: 1550,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Samurai.jpg',
        name: "Samurai",
        hp: 1350,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Storm.jpg',
        name: "Storm",
        hp: 1800,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Tailon.jpg',
        name: "Tailon",
        hp: 1200,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Teslobar.jpg',
        name: "Teslobar",
        hp: 1900,
        damage: 200,
        abilityAvaliable: true,
    },
]

export default champData