const champData = [
    {
        img: '/assets/BoomBot.jpeg',
        name: "BoomBot",
        hp: 1500,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Tigeron.jpeg',
        name: "Tigeron",
        hp: 1000,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Heming.jpeg',
        name: "Heming",
        hp: 1250,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/DragonSkin.jpeg',
        name: "DragonSkin",
        hp: 1400,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Pantheron.jpeg',
        name: "Pantheron",
        hp: 1200,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Higs.jpeg',
        name: "Higs",
        hp: 1700,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/LordOfDarkness.jpeg',
        name: "Lord of darkness",
        hp: 1400,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Meilis.jpeg',
        name: "Meilis",
        hp: 1000,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Returner.jpeg',
        name: "Returner",
        hp: 1550,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Samurai.jpeg',
        name: "Samurai",
        hp: 1350,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Storm.jpeg',
        name: "Storm",
        hp: 1800,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Tailon.jpeg',
        name: "Tailon",
        hp: 1200,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Razal.jpeg',
        name: "Razal",
        hp: 1100,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Ars.jpeg',
        name: "Ars",
        hp: 900,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/MoonKnight.jpeg',
        name: "Moon Knight",
        hp: 1100,
        damage: 250,
        abilityAvaliable: true,
    },
    {
        img:'/assets/KingNolaran.jpeg',
        name: "King Nolaran",
        hp: 1400,
        damage: 200,
        abilityAvaliable: true,
    },
    {
        img:'/assets/Chaos.jpeg',
        name: "Chaos",
        hp: 1900,
        damage: 200,
        abilityAvaliable: false,
    },
    {
        img:'/assets/BlackPanther.jpeg',
        name: "Black Panther",
        hp: 500,
        damage: 200,
        abilityAvaliable: false,
    },
    {
        img:'/assets/George.jpeg',
        name: "George ubrunebs xels sikvdilis win",
        hp: 2200,
        damage: 250,
        abilityAvaliable: false,
    },
]

export default champData